# Generated by Django 4.2.7 on 2025-11-06 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_energy_kwh', models.DecimalField(decimal_places=3, max_digits=10)),
                ('average_power_kw', models.DecimalField(decimal_places=3, max_digits=10)),
                ('peak_power_kw', models.DecimalField(decimal_places=3, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reading_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usage Summary',
                'verbose_name_plural': 'Usage Summaries',
                'ordering': ['-start_date'],
                'unique_together': {('user', 'period_type', 'start_date')},
            },
        ),
        migrations.CreateModel(
            name='EnergyReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('energy_kwh', models.DecimalField(decimal_places=3, help_text='Energy consumed in kWh', max_digits=10)),
                ('power_kw', models.DecimalField(decimal_places=3, help_text='Current power draw in kW', max_digits=10)),
                ('voltage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('current', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('cost', models.DecimalField(decimal_places=2, help_text='Cost in USD', max_digits=10)),
                ('battery_percentage', models.IntegerField(blank=True, null=True)),
                ('battery_status', models.CharField(blank=True, choices=[('charging', 'Charging'), ('discharging', 'Discharging'), ('idle', 'Idle'), ('full', 'Full')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_readings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Energy Reading',
                'verbose_name_plural': 'Energy Readings',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='energy_usag_user_id_c1ebbb_idx'), models.Index(fields=['timestamp'], name='energy_usag_timesta_2e0301_idx')],
            },
        ),
    ]
